blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/yui0118/MyToDo/issues/new?template=custom.md&projects=yui0118%2FMyToDo%2F1&labels=MyToDo
